# Generated by Django 6.0.8 on 2026-08-11 04:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_contractidempotencykey_payload_hash_and_more'),
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('payments', '0002_payment_payment_components_lte_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('phone_call', 'Llamada'), ('whatsapp', 'WhatsApp'), ('visit', 'Visita'), ('sms', 'SMS'), ('email', 'Correo'), ('other', 'Otro')], max_length=20)),
                ('outcome', models.CharField(choices=[('contacted', 'Contactado'), ('no_answer', 'No respondió'), ('promise_to_pay', 'Promesa de pago'), ('wrong_number', 'Número incorrecto'), ('not_found', 'No localizado'), ('refused', 'Se negó'), ('other', 'Otro')], max_length=20)),
                ('notes', models.CharField(max_length=2000)),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('voided', 'Anulada')], default='active', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_actions', to='organizations.branch')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_actions', to='contracts.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_collection_actions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_actions', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_actions', to='organizations.organization')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_collection_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-contact_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promised_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promised_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('fulfilled', 'Cumplida'), ('broken', 'Incumplida'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, max_length=500)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_promises', to='organizations.branch')),
                ('collection_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_promise', to='collection_management.collectionaction')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_promises', to='contracts.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_promises', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_promises', to='customers.customer')),
                ('fulfilled_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_promises', to='payments.payment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_promises', to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_payment_promises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'promised_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CollectionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('action_created', 'Gestión creada'), ('action_voided', 'Gestión anulada'), ('promise_created', 'Promesa creada'), ('promise_fulfilled', 'Promesa cumplida'), ('promise_broken', 'Promesa incumplida'), ('promise_cancelled', 'Promesa cancelada')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='collection_management.collectionaction')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_audits', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_audits', to='organizations.organization')),
                ('promise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='collection_management.paymentpromise')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='collectionaction',
            index=models.Index(fields=['organization', 'contact_date'], name='coll_action_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaction',
            index=models.Index(fields=['branch', 'contact_date'], name='coll_action_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaction',
            index=models.Index(fields=['customer', 'contact_date'], name='coll_action_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaction',
            index=models.Index(fields=['contract', 'contact_date'], name='coll_action_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaction',
            index=models.Index(fields=['status', 'next_follow_up_date'], name='coll_action_follow_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['organization', 'status', 'promised_date'], name='promise_org_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['branch', 'status', 'promised_date'], name='promise_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['customer', 'promised_date'], name='promise_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['contract', 'status'], name='promise_contract_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentpromise',
            constraint=models.CheckConstraint(condition=models.Q(('promised_amount__gt', 0)), name='promise_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='paymentpromise',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('contract',), name='unique_pending_promise_per_contract'),
        ),
        migrations.AddIndex(
            model_name='collectionaudit',
            index=models.Index(fields=['organization', 'created_at'], name='collection_audit_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionaudit',
            constraint=models.CheckConstraint(condition=models.Q(('action__isnull', False), ('promise__isnull', False), _connector='OR'), name='collection_audit_has_target'),
        ),
    ]
