# Generated by Django 6.0.8 on 2026-08-11 05:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0001_initial'),
        ('contracts', '0003_contractidempotencykey_payload_hash_and_more'),
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('payments', '0002_payment_payment_components_lte_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('ended', 'Finalizada'), ('reassigned', 'Reasignada'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_portfolios', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_assignments', to='organizations.branch')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_assignments', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_assignments', to='contracts.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_assignments', to='organizations.organization')),
                ('previous_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_assignment', to='collection_management.collectionassignment')),
            ],
            options={
                'ordering': ('-assigned_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CollectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_routes', to='organizations.branch')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_routes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_collection_routes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_routes', to='organizations.organization')),
            ],
            options={
                'ordering': ('day_of_week', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CollectionRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_route_stops', to='customers.customer')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='collection_management.collectionroute')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CollectionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_zones', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_collection_zones', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_zones', to='organizations.organization')),
            ],
            options={
                'ordering': ('branch__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='collectionroute',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='collection_management.collectionzone'),
        ),
        migrations.CreateModel(
            name='CollectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__first_name', 'user__last_name', 'employee_code'),
            },
        ),
        migrations.CreateModel(
            name='CollectorSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_sequence', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CollectorSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_number', models.CharField(editable=False, max_length=20)),
                ('total_collected', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reported_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('check_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Presentada'), ('reviewed', 'Revisada'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('review_notes', models.CharField(blank=True, max_length=1000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collector_settlements', to='organizations.branch')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collector_settlements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collector_settlements', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_collector_settlements', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_collector_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CollectorSettlementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number_snapshot', models.CharField(max_length=20)),
                ('receipt_number_snapshot', models.CharField(max_length=20)),
                ('customer_name_snapshot', models.CharField(max_length=340)),
                ('contract_number_snapshot', models.CharField(max_length=20)),
                ('payment_method_snapshot', models.CharField(max_length=20)),
                ('amount_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('included_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collector_settlement_item', to='payments.payment')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='collection_management.collectorsettlement')),
            ],
            options={
                'ordering': ('payment__payment_date', 'payment_id'),
            },
        ),
        migrations.CreateModel(
            name='CollectorWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='open', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collector_work_sessions', to='organizations.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_collector_sessions', to=settings.AUTH_USER_MODEL)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collector_work_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_collector_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collector_work_sessions', to='organizations.organization')),
            ],
            options={
                'ordering': ('-work_date', '-started_at'),
            },
        ),
        migrations.AddField(
            model_name='collectorsettlement',
            name='work_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='collection_management.collectorworksession'),
        ),
        migrations.CreateModel(
            name='CollectionOperationsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('profile_created', 'Perfil creado'), ('assignment_created', 'Cartera asignada'), ('assignment_reassigned', 'Cartera reasignada'), ('assignment_ended', 'Asignación finalizada'), ('route_created', 'Ruta creada'), ('route_updated', 'Ruta actualizada'), ('session_started', 'Jornada iniciada'), ('session_closed', 'Jornada cerrada'), ('settlement_submitted', 'Liquidación presentada'), ('settlement_reviewed', 'Liquidación revisada'), ('settlement_accepted', 'Liquidación aceptada'), ('settlement_rejected', 'Liquidación rechazada'), ('settled_payment_voided', 'Pago liquidado anulado')], max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_operations_audits', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_audits', to='collection_management.collectionassignment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_operations_audits', to='organizations.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_operations_audits', to='payments.payment')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_audits', to='collection_management.collectionroute')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_audits', to='collection_management.collectorsettlement')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_audits', to='collection_management.collectorworksession')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerCollectionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_customer_zones', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_zone_links', to='organizations.branch')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection_zone_link', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_zone_links', to='organizations.organization')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_links', to='collection_management.collectionzone')),
            ],
        ),
        migrations.CreateModel(
            name='RouteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('visited', 'Visitado'), ('not_found', 'No encontrado'), ('postponed', 'Pospuesto')], default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('collection_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_visit', to='collection_management.collectionaction')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_visits', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='collection_management.collectionroute')),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='collection_management.collectionroutestop')),
            ],
            options={
                'ordering': ('-visit_date', 'route_stop__position'),
            },
        ),
        migrations.CreateModel(
            name='SettlementSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_sequence', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementSubmissionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_submission_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_submission_keys', to='organizations.organization')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_keys', to='collection_management.collectorsettlement')),
            ],
        ),
        migrations.AddIndex(
            model_name='collectionassignment',
            index=models.Index(fields=['organization', 'status'], name='assign_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionassignment',
            index=models.Index(fields=['branch', 'status'], name='assign_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionassignment',
            index=models.Index(fields=['collector', 'status'], name='assign_collector_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionassignment',
            index=models.Index(fields=['contract', 'status'], name='assign_contract_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('contract',), name='unique_active_collection_assignment'),
        ),
        migrations.AddIndex(
            model_name='collectionroutestop',
            index=models.Index(fields=['route', 'is_active', 'position'], name='route_stop_order_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionroutestop',
            index=models.Index(fields=['customer', 'is_active'], name='route_stop_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionroutestop',
            constraint=models.UniqueConstraint(fields=('route', 'position'), name='unique_route_stop_position'),
        ),
        migrations.AddConstraint(
            model_name='collectionroutestop',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('customer',), name='unique_active_primary_route_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='collectionroutestop',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='route_stop_position_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='collectionzone',
            index=models.Index(fields=['organization', 'is_active'], name='zone_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionzone',
            index=models.Index(fields=['branch', 'is_active'], name='zone_branch_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionzone',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_collection_zone_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='collectionroute',
            index=models.Index(fields=['organization', 'is_active'], name='route_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionroute',
            index=models.Index(fields=['branch', 'day_of_week'], name='route_branch_day_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionroute',
            index=models.Index(fields=['collector', 'is_active'], name='route_collector_active_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionroute',
            index=models.Index(fields=['zone', 'is_active'], name='route_zone_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionroute',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'name'), name='unique_collection_route_name'),
        ),
        migrations.AddIndex(
            model_name='collectorprofile',
            index=models.Index(fields=['is_available'], name='collector_available_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorsettlementpayment',
            index=models.Index(fields=['settlement', 'payment'], name='settlement_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlementpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_snapshot__gt', 0)), name='settlement_payment_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='collectorworksession',
            index=models.Index(fields=['organization', 'work_date'], name='session_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorworksession',
            index=models.Index(fields=['branch', 'work_date'], name='session_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorworksession',
            index=models.Index(fields=['collector', 'status'], name='session_collector_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectorworksession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('organization', 'branch', 'collector'), name='unique_open_collector_work_session'),
        ),
        migrations.AddConstraint(
            model_name='collectorworksession',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'collector', 'work_date'), name='unique_collector_session_per_day'),
        ),
        migrations.AddIndex(
            model_name='collectorsettlement',
            index=models.Index(fields=['organization', 'status'], name='settlement_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorsettlement',
            index=models.Index(fields=['branch', 'status'], name='settlement_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorsettlement',
            index=models.Index(fields=['collector', 'submitted_at'], name='settlement_collector_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlement',
            constraint=models.UniqueConstraint(fields=('organization', 'settlement_number'), name='unique_settlement_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('total_collected__gte', 0)), name='settlement_total_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('expected_cash__gte', 0)), name='settlement_expected_cash_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('reported_cash__gte', 0)), name='settlement_reported_cash_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_total__gte', 0)), name='settlement_transfer_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('card_total__gte', 0)), name='settlement_card_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('check_total__gte', 0)), name='settlement_check_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('other_total__gte', 0)), name='settlement_other_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='collectionoperationsaudit',
            index=models.Index(fields=['organization', 'created_at'], name='operations_audit_org_idx'),
        ),
        migrations.AddIndex(
            model_name='customercollectionzone',
            index=models.Index(fields=['organization', 'zone'], name='cust_zone_org_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='routevisit',
            index=models.Index(fields=['collector', 'visit_date'], name='route_visit_collector_idx'),
        ),
        migrations.AddIndex(
            model_name='routevisit',
            index=models.Index(fields=['route', 'visit_date'], name='route_visit_route_idx'),
        ),
        migrations.AddConstraint(
            model_name='routevisit',
            constraint=models.UniqueConstraint(fields=('route_stop', 'collector', 'visit_date'), name='unique_route_visit_per_day'),
        ),
        migrations.AddConstraint(
            model_name='settlementsubmissionkey',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='unique_settlement_submission_key'),
        ),
    ]
