# Generated by Django 6.0.8 on 2026-08-10 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='draft', max_length=20)),
                ('sale_date', models.DateField()),
                ('start_date', models.DateField()),
                ('plan_name_snapshot', models.CharField(blank=True, max_length=160)),
                ('plan_description_snapshot', models.TextField(blank=True)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=340)),
                ('customer_identity_snapshot', models.CharField(blank=True, max_length=30)),
                ('customer_address_snapshot', models.TextField(blank=True)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=25)),
                ('beneficiary_name_snapshot', models.CharField(blank=True, max_length=340)),
                ('beneficiary_identity_snapshot', models.CharField(blank=True, max_length=30)),
                ('beneficiary_relationship_snapshot', models.CharField(blank=True, max_length=80)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('initial_payment_agreed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('financed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allow_financing', models.BooleanField(default=False)),
                ('payment_frequency', models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('custom', 'Personalizada')], max_length=20)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.beneficiary')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organizations.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='plans.funeralplan')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('draft_created', 'Borrador creado'), ('draft_updated', 'Borrador actualizado'), ('confirmed', 'Contrato confirmado'), ('cancelled', 'Contrato cancelado'), ('pdf_generated', 'PDF generado')], max_length=40)),
                ('description', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='contracts.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('operation', models.CharField(choices=[('create', 'Crear borrador'), ('confirm', 'Confirmar contrato')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='contracts.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_idempotency_keys', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ContractPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code_snapshot', models.CharField(max_length=30)),
                ('service_name_snapshot', models.CharField(max_length=160)),
                ('service_description_snapshot', models.TextField(blank=True)),
                ('category_snapshot', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_snapshot', models.CharField(max_length=80)),
                ('notes_snapshot', models.CharField(blank=True, max_length=240)),
                ('estimated_cost_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='contracts.contract')),
                ('original_plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_snapshots', to='plans.funeralplanitem')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_snapshots', to='plans.funeralserviceitem')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContractSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_sequence', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'status'], name='ctr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['branch', 'sale_date'], name='ctr_branch_sale_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['customer', 'created_at'], name='ctr_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['plan'], name='ctr_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['seller', 'sale_date'], name='ctr_seller_sale_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='ctr_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('organization', 'contract_number'), name='unique_contract_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='contract_subtotal_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='contract_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', models.F('subtotal'))), name='contract_discount_lte_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='contract_total_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('initial_payment_agreed__gte', 0)), name='contract_initial_payment_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('initial_payment_agreed__lte', models.F('total_price'))), name='contract_initial_payment_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('financed_amount__gte', 0)), name='contract_financed_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('allow_financing', True), ('financed_amount', 0), _connector='OR'), name='contract_cash_financed_zero'),
        ),
        migrations.AddIndex(
            model_name='contractactivity',
            index=models.Index(fields=['contract', 'created_at'], name='ctr_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='contractidempotencykey',
            index=models.Index(fields=['organization', 'key'], name='ctr_idempotency_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractidempotencykey',
            constraint=models.UniqueConstraint(fields=('organization', 'key', 'operation'), name='unique_contract_idempotency_operation'),
        ),
        migrations.AddIndex(
            model_name='contractplanitem',
            index=models.Index(fields=['contract', 'sort_order'], name='ctr_item_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='contract_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='contractplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost_snapshot__gte', 0)), name='contract_item_cost_gte_zero'),
        ),
    ]
