# Generated by Django 6.0.8 on 2026-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractactivity',
            name='action',
            field=models.CharField(choices=[('draft_created', 'Borrador creado'), ('draft_updated', 'Borrador actualizado'), ('confirmed', 'Contrato confirmado'), ('cancelled', 'Contrato cancelado'), ('pdf_generated', 'PDF generado'), ('schedule_generated', 'Calendario generado'), ('schedule_reprogrammed', 'Calendario reprogramado'), ('schedule_cancelled', 'Calendario cancelado'), ('schedule_pdf_generated', 'Plan de pagos generado')], max_length=40),
        ),
    ]
