# Generated by Django 6.0.8 on 2026-08-10 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contractactivity_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractidempotencykey',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contractidempotencykey',
            name='resource_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractidempotencykey',
            name='resource_type',
            field=models.CharField(default='contract', max_length=30),
        ),
        migrations.AddField(
            model_name='contractidempotencykey',
            name='response_status',
            field=models.PositiveSmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='contractidempotencykey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractactivity',
            name='action',
            field=models.CharField(choices=[('draft_created', 'Borrador creado'), ('draft_updated', 'Borrador actualizado'), ('confirmed', 'Contrato confirmado'), ('cancelled', 'Contrato cancelado'), ('pdf_generated', 'PDF generado'), ('schedule_generated', 'Calendario generado'), ('schedule_reprogrammed', 'Calendario reprogramado'), ('schedule_cancelled', 'Calendario cancelado'), ('schedule_pdf_generated', 'Plan de pagos generado'), ('payment_created', 'Pago registrado'), ('initial_payment_registered', 'Prima pagada'), ('payment_applied', 'Pago aplicado'), ('settlement_registered', 'Contrato liquidado'), ('receipt_issued', 'Recibo emitido'), ('payment_voided', 'Pago anulado'), ('allocations_rebuilt', 'Aplicaciones reconstruidas')], max_length=40),
        ),
        migrations.AlterField(
            model_name='contractidempotencykey',
            name='operation',
            field=models.CharField(choices=[('create', 'Crear borrador'), ('confirm', 'Confirmar contrato'), ('payment_create', 'Registrar pago')], max_length=20),
        ),
    ]
