# Generated by Django 6.0.8 on 2026-08-08 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('legal_name', models.CharField(blank=True, max_length=220, verbose_name='razón social')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='identificación fiscal')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('address', models.TextField(blank=True, verbose_name='dirección')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='logotipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('code', models.CharField(max_length=30, verbose_name='código')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('address', models.TextField(blank=True, verbose_name='dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organizations.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ('organization__name', 'name'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='unique_branch_code_per_organization')],
            },
        ),
    ]
