# Generated by Django 6.0.8 on 2026-08-10 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_alter_contractactivity_action'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('replaced', 'Reemplazado'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('total_financed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('regular_installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('custom', 'Personalizada')], max_length=20)),
                ('first_due_date', models.DateField()),
                ('last_due_date', models.DateField()),
                ('total_installments', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reprogramming_reason', models.TextField(blank=True)),
                ('reprogrammed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_schedules', to='organizations.branch')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_schedules', to='contracts.contract')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_installment_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_schedules', to='organizations.organization')),
                ('previous_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_schedules', to='installments.installmentschedule')),
                ('reprogrammed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reprogrammed_installment_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('partially_paid', 'Pago parcial'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='organizations.branch')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='contracts.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='organizations.organization')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='installments.installmentschedule')),
            ],
            options={
                'ordering': ('due_date', 'installment_number'),
            },
        ),
        migrations.AddIndex(
            model_name='installmentschedule',
            index=models.Index(fields=['organization', 'status'], name='sch_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentschedule',
            index=models.Index(fields=['contract', 'status'], name='sch_contract_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentschedule',
            index=models.Index(fields=['branch', 'status'], name='sch_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='installmentschedule',
            constraint=models.UniqueConstraint(fields=('contract', 'version'), name='unique_schedule_version_per_contract'),
        ),
        migrations.AddConstraint(
            model_name='installmentschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('contract',), name='unique_active_schedule_per_contract'),
        ),
        migrations.AddConstraint(
            model_name='installmentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='schedule_version_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='installmentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('total_financed__gt', 0)), name='schedule_total_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='installmentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('regular_installment_amount__gt', 0)), name='schedule_regular_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='installmentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('total_installments__gt', 0)), name='schedule_installment_count_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['organization', 'due_date'], name='inst_org_due_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['organization', 'status'], name='inst_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['branch', 'due_date'], name='inst_branch_due_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['contract', 'due_date'], name='inst_contract_due_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['schedule', 'installment_number'], name='inst_schedule_num_idx'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('schedule', 'installment_number'), name='unique_installment_number_per_schedule'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__gt', 0)), name='installment_number_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='installment_original_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='installment_current_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='installment_paid_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('current_amount'))), name='installment_paid_lte_current'),
        ),
    ]
