# Generated by Django 6.0.8 on 2026-08-10 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(editable=False, max_length=20)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('second_last_name', models.CharField(blank=True, max_length=80)),
                ('identity_number', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Femenino'), ('male', 'Masculino'), ('other', 'Otro'), ('unspecified', 'Prefiere no indicar')], max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('partner', 'Unión libre'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a'), ('other', 'Otro')], max_length=20)),
                ('phone', models.CharField(max_length=25)),
                ('secondary_phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, choices=[('atlantida', 'Atlántida'), ('choluteca', 'Choluteca'), ('colon', 'Colón'), ('comayagua', 'Comayagua'), ('copan', 'Copán'), ('cortes', 'Cortés'), ('el_paraiso', 'El Paraíso'), ('francisco_morazan', 'Francisco Morazán'), ('gracias_a_dios', 'Gracias a Dios'), ('intibuca', 'Intibucá'), ('islas_de_la_bahia', 'Islas de la Bahía'), ('la_paz', 'La Paz'), ('lempira', 'Lempira'), ('ocotepeque', 'Ocotepeque'), ('olancho', 'Olancho'), ('santa_barbara', 'Santa Bárbara'), ('valle', 'Valle'), ('yoro', 'Yoro')], max_length=30)),
                ('country', models.CharField(blank=True, default='Honduras', max_length=80)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('second_last_name', models.CharField(blank=True, max_length=80)),
                ('identity_number', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(choices=[('self', 'Titular'), ('spouse', 'Cónyuge'), ('father', 'Padre'), ('mother', 'Madre'), ('son', 'Hijo'), ('daughter', 'Hija'), ('sibling', 'Hermano/a'), ('grandparent', 'Abuelo/a'), ('grandchild', 'Nieto/a'), ('relative', 'Familiar'), ('other', 'Otro')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='customers.customer')),
            ],
            options={
                'ordering': ('first_name', 'last_name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Cliente creado'), ('updated', 'Cliente actualizado'), ('activated', 'Cliente activado'), ('deactivated', 'Cliente inactivado'), ('beneficiary_added', 'Beneficiario agregado'), ('beneficiary_updated', 'Beneficiario actualizado'), ('beneficiary_activated', 'Beneficiario activado'), ('beneficiary_deactivated', 'Beneficiario inactivado'), ('contact_added', 'Contacto agregado'), ('contact_updated', 'Contacto actualizado'), ('contact_activated', 'Contacto activado'), ('contact_deactivated', 'Contacto inactivado')], max_length=40)),
                ('description', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='customers.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(max_length=25)),
                ('secondary_phone', models.CharField(blank=True, max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='customers.customer')),
            ],
            options={
                'ordering': ('-is_primary', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CustomerSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sequence', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'is_active'], name='cust_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='cust_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='cust_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'customer_code'), name='unique_customer_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('identity_number__isnull', False), ('is_active', True)), fields=('organization', 'identity_number'), name='unique_active_customer_identity_per_org'),
        ),
        migrations.AddConstraint(
            model_name='beneficiary',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_customer', True)), fields=('customer',), name='unique_active_self_beneficiary'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['customer', 'created_at'], name='cust_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('customer',), name='unique_active_primary_contact'),
        ),
    ]
