# Generated by Django 6.0.8 on 2026-08-10 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('initial_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allow_financing', models.BooleanField(default=False)),
                ('available_all_branches', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_funeral_plans', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funeral_plans', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FuneralServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('casket', 'Ataúd'), ('preparation', 'Preparación'), ('wake', 'Velatorio'), ('transport', 'Transporte'), ('decoration', 'Decoración'), ('furniture', 'Mobiliario'), ('ceremony', 'Ceremonia'), ('documentation', 'Documentación'), ('cremation', 'Cremación'), ('cemetery', 'Cementerio'), ('other', 'Otros')], max_length=30)),
                ('unit', models.CharField(choices=[('service', 'Servicio'), ('unit', 'Unidad'), ('hour', 'Hora'), ('day', 'Día'), ('kilometer', 'Kilómetro'), ('quantity', 'Cantidad')], default='service', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('default_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_catalog_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_catalog_items', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FuneralPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('included', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='plans.funeralplan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='plans.funeralserviceitem')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='PlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Plan creado'), ('updated', 'Plan actualizado'), ('service_added', 'Prestación agregada'), ('service_removed', 'Prestación retirada'), ('price_changed', 'Precio actualizado'), ('activated', 'Plan reactivado'), ('deactivated', 'Plan inactivado'), ('duplicated', 'Plan duplicado')], max_length=40)),
                ('description', models.CharField(max_length=240)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='plans.funeralplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanBranchAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_funeral_plans', to='organizations.branch')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availabilities', to='plans.funeralplan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sequence', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='funeralplan',
            index=models.Index(fields=['organization', 'is_active'], name='plan_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='funeralplan',
            index=models.Index(fields=['name'], name='plan_name_idx'),
        ),
        migrations.AddIndex(
            model_name='funeralplan',
            index=models.Index(fields=['created_at'], name='plan_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='funeralplan',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_plan_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='funeralplan',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='plan_base_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='funeralplan',
            constraint=models.CheckConstraint(condition=models.Q(('initial_payment__gte', 0)), name='plan_initial_payment_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='funeralserviceitem',
            index=models.Index(fields=['organization', 'is_active'], name='svc_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='funeralserviceitem',
            index=models.Index(fields=['organization', 'category'], name='svc_org_category_idx'),
        ),
        migrations.AddIndex(
            model_name='funeralserviceitem',
            index=models.Index(fields=['name'], name='svc_name_idx'),
        ),
        migrations.AddIndex(
            model_name='funeralserviceitem',
            index=models.Index(fields=['created_at'], name='svc_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='funeralserviceitem',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_service_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='funeralserviceitem',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost__gte', 0)), name='service_estimated_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='funeralserviceitem',
            constraint=models.CheckConstraint(condition=models.Q(('default_sale_price__gte', 0)), name='service_sale_price_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='funeralplanitem',
            index=models.Index(fields=['plan', 'sort_order'], name='plan_item_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='funeralplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'service'), name='unique_service_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='funeralplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='plan_item_quantity_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='planactivity',
            index=models.Index(fields=['plan', 'created_at'], name='plan_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='planbranchavailability',
            constraint=models.UniqueConstraint(fields=('plan', 'branch'), name='unique_plan_branch_availability'),
        ),
    ]
