# Generated by Django 6.0.8 on 2026-08-10 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_contractidempotencykey_payload_hash_and_more'),
        ('customers', '0001_initial'),
        ('installments', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(editable=False, max_length=20)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('payment_type', models.CharField(choices=[('initial_payment', 'Prima'), ('installment', 'Cuota/abono'), ('advance', 'Adelanto'), ('settlement', 'Liquidación'), ('other', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('voided', 'Anulado')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('initial_amount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('direct_amount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organizations.branch')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contracts.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organizations.organization')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-payment_date', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_applications', to='installments.installment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='payments.payment')),
            ],
            options={
                'ordering': ('installment__due_date', 'installment__installment_number'),
            },
        ),
        migrations.CreateModel(
            name='PaymentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sequence', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(editable=False, max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('issued', 'Emitido'), ('voided', 'Anulado')], default='issued', max_length=20)),
                ('organization_name_snapshot', models.CharField(max_length=180)),
                ('organization_address_snapshot', models.TextField(blank=True)),
                ('organization_phone_snapshot', models.CharField(blank=True, max_length=30)),
                ('customer_name_snapshot', models.CharField(max_length=340)),
                ('customer_code_snapshot', models.CharField(max_length=20)),
                ('customer_identity_snapshot', models.CharField(blank=True, max_length=30)),
                ('contract_number_snapshot', models.CharField(max_length=20)),
                ('concept_snapshot', models.CharField(max_length=160)),
                ('method_snapshot', models.CharField(max_length=80)),
                ('reference_snapshot', models.CharField(blank=True, max_length=120)),
                ('received_by_snapshot', models.CharField(max_length=180)),
                ('amount_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applications_snapshot', models.JSONField(default=list)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='organizations.organization')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment')),
            ],
            options={
                'ordering': ('-issued_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_sequence', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'payment_date'], name='pay_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'status'], name='pay_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch', 'payment_date'], name='pay_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['contract', 'payment_date'], name='pay_contract_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'payment_date'], name='pay_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='pay_method_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['received_by', 'payment_date'], name='pay_receiver_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['idempotency_key'], name='pay_idempotency_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('organization', 'payment_number'), name='unique_payment_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='unique_payment_idempotency_per_org'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('initial_amount_applied__gte', 0)), name='payment_initial_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('direct_amount_applied__gte', 0)), name='payment_direct_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('initial_amount_applied__lte', models.F('amount'))), name='payment_initial_lte_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('direct_amount_applied__lte', models.F('amount'))), name='payment_direct_lte_amount'),
        ),
        migrations.AddIndex(
            model_name='paymentapplication',
            index=models.Index(fields=['payment'], name='pay_app_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentapplication',
            index=models.Index(fields=['installment'], name='pay_app_installment_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentapplication',
            constraint=models.UniqueConstraint(fields=('payment', 'installment'), name='unique_payment_application_installment'),
        ),
        migrations.AddConstraint(
            model_name='paymentapplication',
            constraint=models.CheckConstraint(condition=models.Q(('amount_applied__gt', 0)), name='payment_application_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['organization', 'receipt_number'], name='receipt_org_num_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['branch', 'issued_at'], name='receipt_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='receipt_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('organization', 'receipt_number'), name='unique_receipt_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount_snapshot__gt', 0)), name='receipt_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('balance_before__gte', 0)), name='receipt_balance_before_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='receipt_balance_after_gte_zero'),
        ),
    ]
