# Generated by Django 6.0.8 on 2026-08-10 17:04

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contractidempotencykey_payload_hash_and_more'),
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('initial_amount_applied__lte', django.db.models.expressions.CombinedExpression(models.F('amount'), '-', models.F('direct_amount_applied')))), name='payment_components_lte_amount'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after', django.db.models.expressions.CombinedExpression(models.F('balance_before'), '-', models.F('amount_snapshot')))), name='receipt_balance_equation'),
        ),
    ]
