# Generated by Django 6.0.8 on 2026-08-11 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0002_collectionassignment_collectionroute_and_more'),
        ('contracts', '0003_contractidempotencykey_payload_hash_and_more'),
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('payments', '0002_payment_payment_components_lte_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collector_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='collection_management.collectorworksession'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['collector_session', 'status'], name='pay_collector_session_idx'),
        ),
    ]
