# Generated by Django 6.0.8 on 2026-08-11 17:23

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_management', '0002_collectionassignment_collectionroute_and_more'),
        ('organizations', '0001_initial'),
        ('payments', '0003_payment_collector_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cash_registers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='organizations.organization')),
            ],
            options={
                'ordering': ('branch__name', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CashSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_register', models.PositiveBigIntegerField(default=1)),
                ('next_session', models.PositiveBigIntegerField(default=1)),
                ('next_movement', models.PositiveBigIntegerField(default=1)),
                ('next_reception', models.PositiveBigIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sequence', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_number', models.CharField(editable=False, max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cash_in_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cash_out_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_cash_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counted_cash_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('difference_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('method_totals_snapshot', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='organizations.branch')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cash.cashregister')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='organizations.organization')),
            ],
            options={
                'ordering': ('-opened_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference_reason', models.TextField(blank=True)),
                ('movement_fingerprint', models.CharField(max_length=64)),
                ('counted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_counts', to=settings.AUTH_USER_MODEL)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_counts', to='cash.cashsession')),
            ],
            options={
                'ordering': ('-counted_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CollectorSettlementReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reception_number', models.CharField(editable=False, max_length=20)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reported_cash_by_collector', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_received_by_cashier', models.DecimalField(decimal_places=2, max_digits=14)),
                ('collector_difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('delivery_difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_difference_vs_expected', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('check_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada')], default='confirmed', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_receptions', to='organizations.branch')),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_receptions', to='cash.cashsession')),
                ('collector_settlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_reception', to='collection_management.collectorsettlement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_receptions', to='organizations.organization')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_collector_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_number', models.CharField(editable=False, max_length=20)),
                ('movement_type', models.CharField(choices=[('customer_payment', 'Pago de cliente'), ('collector_settlement', 'Liquidación de cobrador'), ('manual_income', 'Ingreso manual'), ('expense', 'Egreso'), ('cash_adjustment', 'Ajuste de caja'), ('other', 'Otro')], max_length=30)),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=10)),
                ('category', models.CharField(choices=[('customer_payment', 'Pago de cliente'), ('collector_settlement', 'Liquidación de cobrador'), ('extraordinary_income', 'Ingreso extraordinario'), ('temporary_contribution', 'Aporte temporal'), ('other_income', 'Otro ingreso'), ('operating_expense', 'Gasto operativo'), ('minor_purchase', 'Compra menor'), ('authorized_refund', 'Devolución autorizada'), ('other_expense', 'Otro egreso')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20)),
                ('affects_cash', models.BooleanField(default=True, editable=False)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('voided', 'Anulado')], default='confirmed', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='organizations.organization')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movement', to='payments.payment')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cash.cashsession')),
                ('settlement_reception', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movement', to='cash.collectorsettlementreception')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CashAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('register_created', 'Caja creada'), ('register_updated', 'Caja actualizada'), ('register_activated', 'Caja activada'), ('register_deactivated', 'Caja inactivada'), ('session_opened', 'Sesión abierta'), ('movement_created', 'Movimiento creado'), ('movement_voided', 'Movimiento anulado'), ('settlement_received', 'Liquidación recibida'), ('count_performed', 'Arqueo realizado'), ('session_closed', 'Sesión cerrada'), ('difference_detected', 'Diferencia detectada')], max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_audits', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_audits', to='organizations.organization')),
                ('cash_count', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='cash.cashcount')),
                ('cash_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='cash.cashmovement')),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='cash.cashregister')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='cash.cashsession')),
                ('settlement_reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='cash.collectorsettlementreception')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CashCountDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denominations', to='cash.cashcount')),
            ],
            options={
                'ordering': ('-denomination',),
                'constraints': [models.UniqueConstraint(fields=('cash_count', 'denomination'), name='unique_cash_count_denomination'), models.CheckConstraint(condition=models.Q(('denomination__gt', 0)), name='cash_denomination_gt_zero'), models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='cash_denomination_subtotal_gte'), models.CheckConstraint(condition=models.Q(('subtotal', django.db.models.expressions.CombinedExpression(models.F('denomination'), '*', models.F('quantity')))), name='cash_denomination_equation')],
            },
        ),
        migrations.CreateModel(
            name='CashIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('operation', models.CharField(choices=[('open_session', 'Abrir sesión'), ('create_income', 'Crear ingreso'), ('create_expense', 'Crear egreso'), ('receive_settlement', 'Recibir liquidación'), ('perform_count', 'Realizar arqueo'), ('close_session', 'Cerrar sesión')], max_length=40)),
                ('payload_hash', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=40)),
                ('resource_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_idempotency_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_idempotency_keys', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='cash_idem_org_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='unique_cash_idempotency_org')],
            },
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['organization', 'is_active'], name='cash_reg_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['branch', 'is_active'], name='cash_reg_branch_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_cash_register_code_org'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['organization', 'status', 'opened_at'], name='cash_session_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['branch', 'status', 'opened_at'], name='cash_session_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['cash_register', 'status'], name='cash_session_register_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['cashier', 'status'], name='cash_session_cashier_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(fields=('organization', 'session_number'), name='unique_cash_session_number_org'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('cash_register',), name='unique_open_session_register'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('branch', 'cashier'), name='unique_open_session_cashier'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('opening_cash__gte', 0)), name='cash_session_opening_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='cashcount',
            index=models.Index(fields=['counted_at'], name='cash_count_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashcount',
            constraint=models.CheckConstraint(condition=models.Q(('expected_cash__gte', 0)), name='cash_count_expected_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='cashcount',
            constraint=models.CheckConstraint(condition=models.Q(('counted_cash__gte', 0)), name='cash_count_counted_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='collectorsettlementreception',
            index=models.Index(fields=['organization', 'received_at'], name='reception_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorsettlementreception',
            index=models.Index(fields=['branch', 'received_at'], name='reception_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collectorsettlementreception',
            index=models.Index(fields=['cash_session', 'status'], name='reception_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlementreception',
            constraint=models.UniqueConstraint(fields=('organization', 'reception_number'), name='unique_reception_number_org'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlementreception',
            constraint=models.CheckConstraint(condition=models.Q(('expected_cash__gte', 0)), name='reception_expected_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlementreception',
            constraint=models.CheckConstraint(condition=models.Q(('reported_cash_by_collector__gte', 0)), name='reception_reported_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='collectorsettlementreception',
            constraint=models.CheckConstraint(condition=models.Q(('cash_received_by_cashier__gte', 0)), name='reception_received_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['organization', 'created_at'], name='cash_move_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['branch', 'created_at'], name='cash_move_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['cash_session', 'status'], name='cash_move_session_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['movement_type', 'direction'], name='cash_move_type_dir_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['payment_method', 'status'], name='cash_move_method_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['payment'], name='cash_move_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.UniqueConstraint(fields=('organization', 'movement_number'), name='unique_cash_movement_number_org'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_movement_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='cashaudit',
            index=models.Index(fields=['organization', 'created_at'], name='cash_audit_org_date_idx'),
        ),
    ]
